//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: vault
// ----------------------------------------------------------------------------
pub mod vault {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for vault
    pub fn program_id() -> Pubkey {
        pubkey!("FbFwrAcdUhxKPWGfR9PMzNr4wvVQnTPYhUWvdjLD3ztU")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Deposit
    // ....................................................................

    /// Main instruction struct for Deposit
    pub struct DepositInstruction {
        pub accounts: DepositInstructionAccountMetas,
        pub data: DepositInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Deposit instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositInstructionAccountMetas {
        pub vault: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Deposit instruction
    #[derive(Debug, Clone)]
    pub struct DepositInstructionAccounts {
        pub vault: Pubkey,

        pub authority: Pubkey,
    }

    impl DepositInstructionAccounts {
        pub fn new(vault: Pubkey, authority: Pubkey) -> Self {
            Self { vault, authority }
        }
    }

    /// Instruction data for Deposit
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositInstructionData {
        pub amount: u64,
    }

    impl DepositInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for DepositInstruction
    impl DepositInstruction {
        fn discriminator() -> [u8; 8] {
            [242u8, 35u8, 198u8, 137u8, 82u8, 225u8, 242u8, 182u8]
        }

        pub fn data(data: DepositInstructionData) -> Self {
            Self {
                accounts: DepositInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositInstructionAccounts) -> Self {
            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub vault: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub vault: Pubkey,

        pub authority: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(vault: Pubkey, authority: Pubkey) -> Self {
            Self { vault, authority }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {
        pub amount: u64,
    }

    impl WithdrawInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: Vault
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Vault {
    pub authority: Pubkey,

    pub balance: u64,
}

impl Vault {
    pub fn new(authority: Pubkey, balance: u64) -> Self {
        Self { authority, balance }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
